### ISSUE TITLE
Make action faster

### ISSUE THREAD

**Issue by sverhoeven** [citation-file-format/cffconvert-github-action#10]
The action took 30s to run at https://github.com/sequgen/sequgen/runs/2176595549?check_suite_focus=true . In the log I saw it was building a Docker image.
I think its quicker to download the image from DockerHub, then to let every run to build the Docker image.

Could the building of the Docker image be moved from the workflow of users repo to whenever a new release is made for this action?

**Comment by jspaaks** [comment]
partly done https://hub.docker.com/r/citationcff/cffconvert, the action still needs to be updated though.

**Comment by jspaaks** [comment]
Done in main, not released yet
