### ISSUE TITLE
Add more jobs to selftest.yml

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cffconvert-github-action#30]
- [x] subdirectory
- [x] conversion
- [x] --validate
- [x] --version
- [x] --help
- [ ] etc ?

**Comment by jspaaks** [comment]
If we can't think of more tests, can this be closed?

**Comment by fdiblen** [comment]
> If we can't think of more tests, can this be closed?

I think the list looks enough.

**Comment by jspaaks** [comment]
Agree, clsoing
