### ISSUE TITLE
List available format for conversion

### ISSUE THREAD

**Issue by abelsiqueira** [citation-file-format/cffconvert-github-action#42]

**Comment by jspaaks** [comment]
Maybe we can print the --help result in the README? Like it is here https://github.com/citation-file-format/cff-converter-python/blob/2.0.0/README.md#command-line-interface

**Comment by abelsiqueira** [comment]
That works for me

**Comment by jspaaks** [comment]
Perhaps near the top of the advanced examples document would be a good place for it

**Comment by abelsiqueira** [comment]
Done
