### ISSUE TITLE
Validation fails for ORCID with letters

### ISSUE THREAD

**Issue by maltelueken** [citation-file-format/cffconvert-github-action#70]
The validation of ORCIDs in CITATION.cff files fails for ORCIDs that contain letters. This seems to be rarely the case, but mine contains an X ("0000-0001-7095-203X"), which leads the validation to fail.

Here is a link to an action workflow that is failing: https://github.com/NLeSC/mcfly/actions/runs/3749747494/jobs/6368574300

**Comment by abelsiqueira** [comment]
See comment on https://github.com/citation-file-format/cff-initializer-javascript/issues/824

The validation works according to the schema version declared in `cff-version`. Changing to the latest schema (1.2.0), should fix it. I've opened https://github.com/NLeSC/mcfly/pull/318 fixing it for mcfly.
